#!/usr/bin/env python3
"""Audit code pretraining/SFT data for quality, leakage, and eval risk.

The script is intentionally streaming-friendly: it can scan multi-GB text
corpora without loading them into memory. It understands the Auralis code
wrapper format:

    <|code|>[python]
    ...
    <|endcode|>

It can also inspect Helix SFT JSONL records and only keep code-related
categories when requested.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import math
import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Iterator


CODE_START_RE = re.compile(r"^<\|code\|>\[(?P<lang>[A-Za-z0-9_+#.-]+)\]\s*$")
CODE_END = "<|endcode|>"
FILENAME_RE = re.compile(r"^<filename>(?P<path>.+)$", re.M)

SECRET_PATTERNS = {
    "aws_access_key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "private_key": re.compile(r"-----BEGIN (?:RSA |OPENSSH |EC |DSA )?PRIVATE KEY-----"),
    "github_token": re.compile(r"\bgh[pousr]_[A-Za-z0-9_]{30,}\b"),
    "generic_token": re.compile(r"(?i)\b(api[_-]?key|secret|token|password|passwd)\b\s*[:=]\s*['\"][^'\"\s]{12,}['\"]"),
}

GENERATED_RE = re.compile(
    r"(?i)\b("
    r"auto[- ]?generated|generated by|do not edit|compiled from|webpackBootstrap|"
    r"minified|sourceMappingURL|protobuf generated|eslint-disable"
    r")\b"
)
VENDOR_RE = re.compile(r"(?i)(^|/)(node_modules|vendor|dist|build|third_party|externals|site-packages)(/|$)")
LICENSE_RE = re.compile(r"(?i)\b(mit license|apache license|gnu general public license|copyright)\b")
HTML_RE = re.compile(r"(?i)</?(html|body|div|script|style|span|table)\b|&(?:nbsp|lt|gt|amp);")
URL_RE = re.compile(r"https?://|www\.")
NOTEBOOK_RE = re.compile(r'"cells"\s*:\s*\[|"nbformat"\s*:')
LOG_RE = re.compile(r"(?i)\b(traceback \(most recent call last\)|exception in thread|stack trace|error:|warning:)\b")
TODO_RE = re.compile(r"(?i)\b(todo|fixme|hack|xxx)\b")
FENCED_CODE_RE = re.compile(
    r"(?:```|''')(?P<lang>[A-Za-z0-9_+#.-]*)\n(?P<code>.*?)(?:```|''')",
    re.S,
)


@dataclass
class Doc:
    source: str
    index: int
    text: str
    lang: str = "unknown"
    category: str = ""
    origin: str = ""


@dataclass
class Audit:
    input_files: list[str]
    docs_seen: int = 0
    docs_audited: int = 0
    bytes_seen: int = 0
    languages: Counter[str] = field(default_factory=Counter)
    categories: Counter[str] = field(default_factory=Counter)
    flags: Counter[str] = field(default_factory=Counter)
    flag_by_lang: dict[str, Counter[str]] = field(default_factory=lambda: defaultdict(Counter))
    duplicate_hashes: int = 0
    exact_hashes_seen: set[str] = field(default_factory=set)
    simhash_buckets: Counter[str] = field(default_factory=Counter)
    samples: dict[str, list[dict]] = field(default_factory=lambda: defaultdict(list))
    python_syntax: Counter[str] = field(default_factory=Counter)

    def add_flag(self, doc: Doc, flag: str) -> None:
        self.flags[flag] += 1
        self.flag_by_lang[doc.lang][flag] += 1
        if len(self.samples[flag]) < 8:
            self.samples[flag].append(sample_doc(doc, flag))


def stable_hash(text: str) -> str:
    compact = "\n".join(line.rstrip() for line in text.strip().splitlines() if line.strip())
    return hashlib.sha1(compact.encode("utf-8", errors="ignore")).hexdigest()


def simple_simhash_bucket(text: str) -> str:
    words = re.findall(r"[A-Za-z_][A-Za-z0-9_]{2,}", text.lower())
    if not words:
        return "empty"
    counts = Counter(words[:2000])
    top = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[:32]
    digest = hashlib.sha1(" ".join(w for w, _ in top).encode("utf-8")).hexdigest()
    return digest[:8]


def sample_doc(doc: Doc, reason: str) -> dict:
    filename = ""
    match = FILENAME_RE.search(doc.text)
    if match:
        filename = match.group("path")[:240]
    preview = doc.text.strip().replace("\r", "")
    if len(preview) > 1200:
        preview = preview[:1200] + "\n...[truncated]"
    return {
        "reason": reason,
        "source": doc.source,
        "index": doc.index,
        "lang": doc.lang,
        "category": doc.category,
        "origin": doc.origin,
        "filename": filename,
        "chars": len(doc.text),
        "preview": preview,
    }


def iter_code_wrapped(path: Path) -> Iterator[Doc]:
    index = 0
    in_doc = False
    lang = "unknown"
    buf: list[str] = []
    with path.open("r", encoding="utf-8", errors="replace", buffering=1024 * 1024) as fh:
        for raw in fh:
            line = raw.rstrip("\n")
            if not in_doc:
                match = CODE_START_RE.match(line)
                if match:
                    in_doc = True
                    lang = match.group("lang").lower()
                    buf = []
                continue
            if line == CODE_END:
                index += 1
                yield Doc(source=str(path), index=index, text="\n".join(buf), lang=lang)
                in_doc = False
                lang = "unknown"
                buf = []
            else:
                buf.append(line)
    if in_doc and buf:
        index += 1
        yield Doc(source=str(path), index=index, text="\n".join(buf), lang=lang)


def infer_lang_from_text(text: str) -> str:
    if re.search(r"^\s*def\s+\w+\(|^\s*import\s+\w+|^\s*from\s+\w+\s+import\b", text, re.M):
        return "python"
    if re.search(r"\bfunction\s+\w+\(|\bconst\s+\w+\s*=|=>", text):
        return "javascript"
    if re.search(r"\bfn\s+\w+\(|\blet\s+mut\b|use\s+std::", text):
        return "rust"
    if re.search(r"#include\s*<|std::|int\s+main\s*\(", text):
        return "cpp"
    if re.search(r"\bpublic\s+class\b|\bSystem\.out\.println\b", text):
        return "java"
    if re.search(r"\bSELECT\b.+\bFROM\b|\bCREATE\s+TABLE\b", text, re.I | re.S):
        return "sql"
    if re.search(r"^\s*#!/bin/(?:ba)?sh|^\s*(?:set -e|fi|done)\b", text, re.M):
        return "shell"
    return "unknown"


def extract_code_for_syntax(doc: Doc) -> str:
    """Return the code part that should be syntax-checked.

    Raw pretraining docs contain repository metadata markers such as
    ``<filename>`` and ``<reponame>``. SFT records contain chat text and fenced
    snippets. Checking the entire record would over-report syntax errors.
    """
    text = doc.text
    blocks = []
    for match in FENCED_CODE_RE.finditer(text):
        lang = (match.group("lang") or "").lower().strip()
        if doc.lang == "python" or lang in {"python", "py"}:
            blocks.append(match.group("code"))
    if blocks:
        return "\n\n".join(blocks)

    lines = []
    for line in text.splitlines():
        if line.startswith("<filename>") or line.startswith("<reponame>"):
            continue
        if line.startswith("<|"):
            continue
        lines.append(line)
    return "\n".join(lines)


def iter_helix_jsonl(path: Path, code_only: bool) -> Iterator[Doc]:
    with path.open("r", encoding="utf-8", errors="replace", buffering=1024 * 1024) as fh:
        for index, raw in enumerate(fh, start=1):
            try:
                rec = json.loads(raw)
            except json.JSONDecodeError:
                continue
            text = rec.get("text") or ""
            category = str(rec.get("category") or "")
            if code_only and "code" not in category.lower() and "coding" not in category.lower():
                continue
            lang = infer_lang_from_text(text)
            yield Doc(
                source=str(path),
                index=index,
                text=text,
                lang=lang,
                category=category,
                origin=str(rec.get("source") or ""),
            )


def iter_plain_lines(path: Path) -> Iterator[Doc]:
    with path.open("r", encoding="utf-8", errors="replace", buffering=1024 * 1024) as fh:
        for index, raw in enumerate(fh, start=1):
            text = raw.rstrip("\n")
            if text:
                yield Doc(source=str(path), index=index, text=text, lang=infer_lang_from_text(text))


def iter_docs(path: Path, mode: str, code_only: bool) -> Iterator[Doc]:
    if mode == "code-wrapped":
        yield from iter_code_wrapped(path)
    elif mode == "helix-jsonl":
        yield from iter_helix_jsonl(path, code_only=code_only)
    elif mode == "plain-lines":
        yield from iter_plain_lines(path)
    else:
        suffix = path.suffix.lower()
        if suffix == ".jsonl":
            yield from iter_helix_jsonl(path, code_only=code_only)
            return
        # Peek for wrapper marker.
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            head = fh.read(2048)
        if "<|code|>" in head:
            yield from iter_code_wrapped(path)
        else:
            yield from iter_plain_lines(path)


def line_length_stats(text: str) -> tuple[int, int, float]:
    lines = text.splitlines() or [text]
    lengths = [len(line) for line in lines]
    long_lines = sum(1 for n in lengths if n > 240)
    avg = sum(lengths) / max(1, len(lengths))
    return len(lines), long_lines, avg


def audit_doc(doc: Doc, audit: Audit) -> None:
    audit.docs_audited += 1
    audit.bytes_seen += len(doc.text.encode("utf-8", errors="ignore"))
    audit.languages[doc.lang] += 1
    if doc.category:
        audit.categories[doc.category] += 1

    text = doc.text
    stripped = text.strip()
    lines, long_lines, avg_line_len = line_length_stats(text)
    char_len = len(text)

    if char_len < 80:
        audit.add_flag(doc, "too_short_fragment")
    if char_len > 80_000:
        audit.add_flag(doc, "too_long_file")
    if "\ufffd" in text:
        audit.add_flag(doc, "replacement_chars")
    if any((ord(ch) < 32 and ch not in "\n\r\t") for ch in text):
        audit.add_flag(doc, "control_chars")
    if lines <= 2 and char_len > 800:
        audit.add_flag(doc, "collapsed_or_minified")
    if long_lines >= max(3, math.ceil(lines * 0.20)) or avg_line_len > 180:
        audit.add_flag(doc, "long_line_dense")
    if GENERATED_RE.search(text):
        audit.add_flag(doc, "generated_or_compiled")
    if NOTEBOOK_RE.search(text):
        audit.add_flag(doc, "notebook_json")
    if HTML_RE.search(text):
        audit.add_flag(doc, "html_embedded")
    if LOG_RE.search(text):
        audit.add_flag(doc, "log_or_traceback")
    if URL_RE.search(text) and len(URL_RE.findall(text)) >= 3:
        audit.add_flag(doc, "url_dense")
    if LICENSE_RE.search(text) and char_len < 5000:
        audit.add_flag(doc, "license_boilerplate")
    if TODO_RE.search(text) and len(TODO_RE.findall(text)) >= 8:
        audit.add_flag(doc, "todo_dense")

    filename_match = FILENAME_RE.search(text)
    if filename_match and VENDOR_RE.search(filename_match.group("path")):
        audit.add_flag(doc, "vendor_or_dependency_path")

    for name, pattern in SECRET_PATTERNS.items():
        if pattern.search(text):
            audit.add_flag(doc, f"possible_secret_{name}")

    h = stable_hash(stripped)
    if h in audit.exact_hashes_seen:
        audit.duplicate_hashes += 1
        audit.add_flag(doc, "exact_duplicate")
    else:
        audit.exact_hashes_seen.add(h)

    bucket = simple_simhash_bucket(text)
    audit.simhash_buckets[bucket] += 1
    if audit.simhash_buckets[bucket] == 5:
        audit.add_flag(doc, "near_duplicate_bucket")

    if doc.lang == "python":
        code = extract_code_for_syntax(doc)
        try:
            ast.parse(code)
        except SyntaxError:
            audit.python_syntax["syntax_error"] += 1
            audit.add_flag(doc, "python_syntax_error")
        else:
            audit.python_syntax["ok"] += 1


def score_payload(audit: Audit) -> dict:
    total = max(1, audit.docs_audited)
    high_risk = sum(
        audit.flags[k]
        for k in audit.flags
        if k.startswith("possible_secret_")
        or k in {
            "control_chars",
            "replacement_chars",
            "notebook_json",
            "generated_or_compiled",
            "vendor_or_dependency_path",
            "python_syntax_error",
            "collapsed_or_minified",
        }
    )
    return {
        "docs_audited": audit.docs_audited,
        "bytes_seen": audit.bytes_seen,
        "languages": dict(audit.languages.most_common()),
        "categories": dict(audit.categories.most_common()),
        "flags": dict(audit.flags.most_common()),
        "flag_rates": {k: round(v * 100 / total, 4) for k, v in audit.flags.most_common()},
        "flag_by_lang": {lang: dict(counter.most_common()) for lang, counter in audit.flag_by_lang.items()},
        "exact_duplicate_hashes": audit.duplicate_hashes,
        "python_syntax": dict(audit.python_syntax),
        "high_risk_flag_events": high_risk,
        "high_risk_event_rate_pct": round(high_risk * 100 / total, 4),
        "samples": audit.samples,
    }


def write_markdown(payload: dict, output: Path) -> None:
    lines = [
        "# Code Corpus Audit",
        "",
        f"- Docs audited: {payload['docs_audited']:,}",
        f"- Bytes scanned: {payload['bytes_seen'] / 1e9:.3f} GB",
        f"- High-risk flag events: {payload['high_risk_flag_events']:,} ({payload['high_risk_event_rate_pct']}%)",
        f"- Exact duplicate docs: {payload['exact_duplicate_hashes']:,}",
        "",
        "## Languages",
        "",
    ]
    for lang, count in payload["languages"].items():
        lines.append(f"- {lang}: {count:,}")
    lines += ["", "## Flags", ""]
    for flag, count in payload["flags"].items():
        rate = payload["flag_rates"].get(flag, 0)
        lines.append(f"- {flag}: {count:,} ({rate}%)")
    lines += ["", "## Python Syntax", ""]
    for key, count in payload["python_syntax"].items():
        lines.append(f"- {key}: {count:,}")
    lines += ["", "## Sample Findings", ""]
    for flag, samples in payload["samples"].items():
        lines.append(f"### {flag}")
        for sample in samples[:5]:
            lines.append("")
            lines.append(
                f"- source={sample['source']} index={sample['index']} lang={sample['lang']} "
                f"category={sample['category']} filename={sample['filename']}"
            )
            preview = sample["preview"].replace("```", "'''")
            lines.append("")
            lines.append("```text")
            lines.append(preview)
            lines.append("```")
        lines.append("")
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit code corpora/SFT data.")
    parser.add_argument("--input", nargs="+", type=Path, required=True)
    parser.add_argument("--mode", choices=["auto", "code-wrapped", "helix-jsonl", "plain-lines"], default="auto")
    parser.add_argument("--code-only", action="store_true", help="For Helix JSONL, only inspect code-related categories.")
    parser.add_argument("--max-docs", type=int, default=0, help="Stop after this many audited docs across inputs.")
    parser.add_argument("--output-json", type=Path, required=True)
    parser.add_argument("--output-md", type=Path, required=True)
    args = parser.parse_args()

    audit = Audit(input_files=[str(p) for p in args.input])
    for path in args.input:
        for doc in iter_docs(path, args.mode, code_only=args.code_only):
            audit.docs_seen += 1
            audit_doc(doc, audit)
            if args.max_docs and audit.docs_audited >= args.max_docs:
                payload = score_payload(audit)
                args.output_json.parent.mkdir(parents=True, exist_ok=True)
                args.output_md.parent.mkdir(parents=True, exist_ok=True)
                args.output_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
                write_markdown(payload, args.output_md)
                return

    payload = score_payload(audit)
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_md.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    write_markdown(payload, args.output_md)


if __name__ == "__main__":
    main()
