#!/usr/bin/env python3
"""Download small, auditable public code sources for Auralis.

This script is intentionally conservative: it writes manifests and reject
samples and is meant to produce candidates that are then passed through
``filter_code_corpus.py`` before they enter any training mix.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


CODE_BYTES_PER_TOKEN = 3.5
DEFAULT_ALLOWED_LICENSES = {
    "apache-2.0",
    "mit",
    "bsd-3-clause",
    "bsd-2-clause",
    "isc",
    "cc0-1.0",
    "unlicense",
}
GENERATED_RE = re.compile(
    r"(?i)\b(auto[- ]?generated|generated by|do not edit|compiled from|"
    r"webpackBootstrap|minified|sourceMappingURL|protobuf generated)\b"
)
VENDOR_RE = re.compile(r"(?i)(^|/)(node_modules|vendor|dist|build|third_party|externals|site-packages)(/|$)")
SECRET_RE = re.compile(
    r"(?i)\b(api[_-]?key|secret|token|password|passwd)\b\s*[:=]\s*['\"][^'\"\s]{12,}['\"]|"
    r"-----BEGIN (?:RSA |OPENSSH |EC |DSA )?PRIVATE KEY-----|"
    r"\bAKIA[0-9A-Z]{16}\b"
)
LICENSE_HINT_RE = re.compile(r"(?i)\b(copyright|license|apache|mit license|bsd license|gpl|mozilla public license)\b")


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def load_streaming_dataset(path: str, split: str):
    from datasets import load_dataset

    token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_HUB_TOKEN")
    kwargs: dict[str, Any] = {"split": split, "streaming": True}
    if token:
        kwargs["token"] = token
    return load_dataset(path, **kwargs)


def strip_leading_license_comments(text: str) -> str:
    """Remove a leading comment-only license banner from Python files.

    The goal is not legal normalization; it is to reduce repeated boilerplate
    tokens. We only strip a contiguous leading block of comments/blank lines
    when that block contains obvious license/copyright words.
    """
    lines = text.replace("\r\n", "\n").splitlines()
    if not lines:
        return text
    end = 0
    saw_comment = False
    for i, line in enumerate(lines[:80]):
        stripped = line.strip()
        if not stripped:
            end = i + 1
            continue
        if stripped.startswith("#") or stripped in {'"""', "'''"}:
            saw_comment = True
            end = i + 1
            continue
        break
    if not saw_comment or end == 0:
        return text
    banner = "\n".join(lines[:end])
    if not LICENSE_HINT_RE.search(banner):
        return text
    return "\n".join(lines[end:]).lstrip("\n")


def reject_codeparrot_record(
    ex: dict[str, Any],
    min_chars: int,
    max_chars: int,
    allowed_licenses: set[str] | None,
) -> list[str]:
    reasons: list[str] = []
    content = ex.get("content") or ""
    path = str(ex.get("path") or "")
    license_name = str(ex.get("license") or "unknown").lower()
    if allowed_licenses is not None and license_name not in allowed_licenses:
        reasons.append("license_not_allowed")
    if len(content) < min_chars:
        reasons.append("too_short")
    if len(content) > max_chars:
        reasons.append("too_long")
    if ex.get("autogenerated") is True:
        reasons.append("autogenerated_field")
    copies = ex.get("copies")
    if isinstance(copies, (int, float)) and copies > 5:
        reasons.append("too_many_copies")
    line_max = ex.get("line_max")
    if isinstance(line_max, (int, float)) and line_max > 300:
        reasons.append("long_line_field")
    line_mean = ex.get("line_mean")
    if isinstance(line_mean, (int, float)) and line_mean > 140:
        reasons.append("high_mean_line_length")
    if VENDOR_RE.search(path):
        reasons.append("vendor_path")
    if GENERATED_RE.search(content):
        reasons.append("generated_or_compiled")
    if SECRET_RE.search(content):
        reasons.append("possible_secret")
    try:
        ast.parse(content)
    except SyntaxError:
        reasons.append("python_syntax_error")
    return reasons


def download_codeparrot_clean(args: argparse.Namespace) -> dict[str, Any]:
    ds = load_streaming_dataset("codeparrot/codeparrot-clean", split="train")
    allowed_licenses = None
    if args.allowed_licenses and args.allowed_licenses != ["all"]:
        allowed_licenses = {x.lower() for x in args.allowed_licenses}
    stats: dict[str, Any] = {
        "source": "codeparrot/codeparrot-clean",
        "dataset_kind": "raw_python_code",
        "started_at": now_iso(),
        "output": str(args.output),
        "max_docs": args.max_docs,
        "target_bytes": args.target_bytes,
        "filters": {
            "min_chars": args.min_chars,
            "max_chars": args.max_chars,
            "skip_autogenerated": True,
            "max_copies": 5,
            "python_ast_parse": True,
            "allowed_licenses": sorted(allowed_licenses) if allowed_licenses is not None else "all",
            "strip_leading_license_comments": not args.keep_license_headers,
        },
        "seen": 0,
        "kept": 0,
        "bytes_kept": 0,
        "reject_reasons": Counter(),
        "licenses": Counter(),
    }
    reject_samples: list[dict[str, Any]] = []
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as out:
        for ex in ds:
            stats["seen"] += 1
            content = (ex.get("content") or "").replace("\r\n", "\n")
            if not args.keep_license_headers:
                content = strip_leading_license_comments(content)
                ex = {**ex, "content": content}
            reasons = reject_codeparrot_record(
                ex,
                min_chars=args.min_chars,
                max_chars=args.max_chars,
                allowed_licenses=allowed_licenses,
            )
            license_name = str(ex.get("license") or "unknown")
            stats["licenses"][license_name] += 1
            if reasons:
                for reason in reasons:
                    stats["reject_reasons"][reason] += 1
                if len(reject_samples) < args.reject_sample_limit:
                    reject_samples.append(
                        {
                            "index": stats["seen"],
                            "path": ex.get("path"),
                            "repo_name": ex.get("repo_name"),
                            "license": license_name,
                            "reasons": reasons,
                            "preview": content[:800],
                        }
                    )
            else:
                path = str(ex.get("path") or "")
                repo = str(ex.get("repo_name") or "")
                wrapped = f"<|code|>[python]\n<filename>{path}\n<reponame>{repo}\n{content.rstrip()}\n<|endcode|>\n"
                out.write(wrapped)
                stats["kept"] += 1
                stats["bytes_kept"] += len(wrapped.encode("utf-8"))
            if args.max_docs and stats["seen"] >= args.max_docs:
                break
            if args.target_bytes and stats["bytes_kept"] >= args.target_bytes:
                break
    stats["finished_at"] = now_iso()
    stats["estimated_tokens"] = int(stats["bytes_kept"] / CODE_BYTES_PER_TOKEN)
    stats["reject_reasons"] = dict(stats["reject_reasons"].most_common())
    stats["licenses"] = dict(stats["licenses"].most_common(30))
    if args.manifest:
        write_json(args.manifest, stats)
    if args.reject_samples:
        args.reject_samples.parent.mkdir(parents=True, exist_ok=True)
        args.reject_samples.write_text(
            "\n".join(json.dumps(x, ensure_ascii=False) for x in reject_samples) + ("\n" if reject_samples else ""),
            encoding="utf-8",
        )
    return stats


def usable_reasoning_record(ex: dict[str, Any], min_pass_rate: float) -> tuple[bool, list[str]]:
    reasons: list[str] = []
    question = str(ex.get("question") or "").strip()
    solution = str(ex.get("solution") or "").strip()
    generation = str(ex.get("r1_generation") or "").strip()
    pass_rate = ex.get("pass_rate")
    if not question or question == "-":
        reasons.append("empty_question")
    if not solution and not generation:
        reasons.append("empty_solution")
    if isinstance(pass_rate, (int, float)) and pass_rate < min_pass_rate:
        reasons.append("low_pass_rate")
    return not reasons, reasons


def download_open_code_reasoning(args: argparse.Namespace) -> dict[str, Any]:
    ds = load_streaming_dataset("nvidia/OpenCodeReasoning-2", split=args.reasoning_split)
    stats: dict[str, Any] = {
        "source": "nvidia/OpenCodeReasoning-2",
        "dataset_kind": "code_reasoning_sft_candidate",
        "split": args.reasoning_split,
        "started_at": now_iso(),
        "output": str(args.output),
        "max_docs": args.max_docs,
        "filters": {"min_pass_rate": args.min_pass_rate},
        "seen": 0,
        "kept": 0,
        "bytes_kept": 0,
        "reject_reasons": Counter(),
        "sources": Counter(),
        "difficulties": Counter(),
    }
    reject_samples: list[dict[str, Any]] = []
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as out:
        for ex in ds:
            stats["seen"] += 1
            stats["sources"][str(ex.get("source") or "unknown")] += 1
            stats["difficulties"][str(ex.get("difficulty") or "unknown")] += 1
            ok, reasons = usable_reasoning_record(ex, min_pass_rate=args.min_pass_rate)
            if not ok:
                for reason in reasons:
                    stats["reject_reasons"][reason] += 1
                if len(reject_samples) < args.reject_sample_limit:
                    reject_samples.append(
                        {
                            "index": stats["seen"],
                            "id": ex.get("id"),
                            "source": ex.get("source"),
                            "difficulty": ex.get("difficulty"),
                            "pass_rate": ex.get("pass_rate"),
                            "reasons": reasons,
                            "question_preview": str(ex.get("question") or "")[:500],
                        }
                    )
            else:
                answer = str(ex.get("solution") or ex.get("r1_generation") or "").strip()
                text = (
                    "<|user|>\n"
                    f"{str(ex.get('question') or '').strip()}\n"
                    "<|assistant|>\n"
                    f"{answer}\n"
                    "<|end|>"
                )
                rec = {
                    "text": text,
                    "category": "code_reasoning_disjoint_candidate",
                    "source": "nvidia/OpenCodeReasoning-2",
                    "origin": ex.get("source"),
                    "difficulty": ex.get("difficulty"),
                    "pass_rate": ex.get("pass_rate"),
                    "question_id": ex.get("question_id"),
                    "license": ex.get("license"),
                }
                raw = json.dumps(rec, ensure_ascii=False)
                out.write(raw + "\n")
                stats["kept"] += 1
                stats["bytes_kept"] += len(raw.encode("utf-8")) + 1
            if args.max_docs and stats["seen"] >= args.max_docs:
                break
    stats["finished_at"] = now_iso()
    stats["reject_reasons"] = dict(stats["reject_reasons"].most_common())
    stats["sources"] = dict(stats["sources"].most_common(30))
    stats["difficulties"] = dict(stats["difficulties"].most_common(30))
    if args.manifest:
        write_json(args.manifest, stats)
    if args.reject_samples:
        args.reject_samples.parent.mkdir(parents=True, exist_ok=True)
        args.reject_samples.write_text(
            "\n".join(json.dumps(x, ensure_ascii=False) for x in reject_samples) + ("\n" if reject_samples else ""),
            encoding="utf-8",
        )
    return stats


def main() -> None:
    parser = argparse.ArgumentParser(description="Download auditable public code data candidates.")
    parser.add_argument("--source", choices=["codeparrot-clean", "opencodereasoning2"], required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, default=None)
    parser.add_argument("--reject-samples", type=Path, default=None)
    parser.add_argument("--reject-sample-limit", type=int, default=200)
    parser.add_argument("--max-docs", type=int, default=10_000)
    parser.add_argument("--target-bytes", type=int, default=0)
    parser.add_argument("--min-chars", type=int, default=300)
    parser.add_argument("--max-chars", type=int, default=60_000)
    parser.add_argument(
        "--allowed-licenses",
        nargs="+",
        default=sorted(DEFAULT_ALLOWED_LICENSES),
        help="Allowed license ids for codeparrot-clean, or 'all'.",
    )
    parser.add_argument("--keep-license-headers", action="store_true")
    parser.add_argument("--reasoning-split", default="python")
    parser.add_argument("--min-pass-rate", type=float, default=0.0)
    args = parser.parse_args()

    if args.source == "codeparrot-clean":
        stats = download_codeparrot_clean(args)
    else:
        stats = download_open_code_reasoning(args)
    print(json.dumps({k: v for k, v in stats.items() if k not in {"licenses", "sources"}}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
