#!/usr/bin/env python3
"""Download and audit additional v6 data candidates.

The outputs stay source-separated. This script is deliberately conservative:
it writes candidates and manifests, but does not promote anything into a final
training mix.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import time
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from statistics import median
from typing import Any, Iterable

from datasets import load_dataset


BAD_RE = re.compile(
    r"\[(?:deleted|removed)\]|onlyfans|discord\.gg|telegram|whatsapp|free karma|"
    r"subscribe to|promo code|coupon code|buy now|nsfw|porn|sexkontakte|casino|"
    r"sportwetten|warenkorb|rabattcode|cookie policy|xxxHHxxx",
    re.I,
)
URL_RE = re.compile(r"https?://|www\.", re.I)
HTML_RE = re.compile(r"<\s*/?\s*(html|body|div|script|style|iframe)\b|href=|&(?:amp|gt|lt|quot);", re.I)
BOILER_RE = re.compile(r"\b(cookie|privacy policy|datenschutz|impressum|all rights reserved)\b", re.I)
COMMERCE_RE = re.compile(r"\b(warenkorb|rabatt|gutschein|checkout|kaufen|shop|preis|rabatt)\b", re.I)
LIST_TABLE_RE = re.compile(r"(^|\s)([-*]|\d{1,3}[.)])\s+|\|\s*[-:]+\s*\||\t|\.{3,}\s*\d{1,5}", re.I)
DE_RE = re.compile(r"\b(der|die|das|und|ist|nicht|frage|antwort|schritt|erklaere|erklare|wird|werden)\b", re.I)
EN_RE = re.compile(r"\b(the|and|you|write|explain|answer|question|therefore|because)\b", re.I)
SECRET_RE = re.compile(
    r"(?i)\b(api[_-]?key|secret|token|password|passwd)\b\s*[:=]\s*['\"][^'\"\s]{12,}['\"]|"
    r"-----BEGIN (?:RSA |OPENSSH |EC |DSA )?PRIVATE KEY-----|"
    r"\bAKIA[0-9A-Z]{16}\b"
)
GENERATED_CODE_RE = re.compile(r"(?i)\b(auto[- ]?generated|generated by|do not edit|minified|sourceMappingURL)\b")
VENDOR_PATH_RE = re.compile(r"(?i)(^|/)(node_modules|vendor|dist|build|third_party|externals|site-packages)(/|$)")
ALLOWED_CODE_LICENSES = {"apache-2.0", "mit", "bsd-3-clause", "bsd-2-clause", "isc", "cc0-1.0", "unlicense"}


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def clean(text: Any) -> str:
    text = str(text or "").replace("\r\n", "\n").replace("\r", "\n").replace("\x00", "")
    text = re.sub(r"[ \t]{2,}", " ", text)
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    return text.strip()


def one_line(text: str) -> str:
    return re.sub(r"\s+", " ", clean(text)).strip()


def norm_hash(text: str) -> str:
    import hashlib

    norm = re.sub(r"\s+", " ", text).strip().lower()
    return hashlib.sha256(norm.encode("utf-8", errors="replace")).hexdigest()


def hf_kwargs(streaming: bool = True) -> dict[str, Any]:
    kwargs: dict[str, Any] = {"streaming": streaming}
    token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_HUB_TOKEN")
    if token:
        kwargs["token"] = token
    return kwargs


def parse_license(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(x) for x in value]
    if isinstance(value, str) and value.startswith("["):
        try:
            parsed = ast.literal_eval(value)
            if isinstance(parsed, list):
                return [str(x) for x in parsed]
        except Exception:
            return [value]
    return [str(value)] if value else []


class Writer:
    def __init__(self, out_dir: Path, name: str, text_name: str | None = None) -> None:
        self.dir = out_dir / name
        self.dir.mkdir(parents=True, exist_ok=True)
        self.jsonl_path = self.dir / f"{name}.jsonl"
        self.txt_path = self.dir / f"{text_name or name}.txt"
        self.reject_path = self.dir / f"{name}.reject_samples.jsonl"
        self.jsonl = self.jsonl_path.open("w", encoding="utf-8", newline="\n")
        self.txt = self.txt_path.open("w", encoding="utf-8", newline="\n")
        self.rejects: list[dict[str, Any]] = []
        self.hashes: Counter[str] = Counter()
        self.lengths: list[int] = []

    def write(self, rec: dict[str, Any], text: str) -> None:
        self.jsonl.write(json.dumps(rec, ensure_ascii=False, sort_keys=True) + "\n")
        self.txt.write(text.rstrip() + "\n\n")
        self.hashes[norm_hash(text)] += 1
        self.lengths.append(len(text))

    def reject(self, sample: dict[str, Any]) -> None:
        if len(self.rejects) < 200:
            self.rejects.append(sample)

    def close(self) -> dict[str, Any]:
        self.jsonl.close()
        self.txt.close()
        if self.rejects:
            self.reject_path.write_text(
                "\n".join(json.dumps(x, ensure_ascii=False, sort_keys=True) for x in self.rejects) + "\n",
                encoding="utf-8",
            )
        lengths = sorted(self.lengths)
        dupes = sum(c - 1 for c in self.hashes.values() if c > 1)
        return {
            "jsonl": str(self.jsonl_path),
            "txt": str(self.txt_path),
            "reject_samples": str(self.reject_path) if self.rejects else None,
            "bytes_jsonl": self.jsonl_path.stat().st_size,
            "bytes_txt": self.txt_path.stat().st_size,
            "unique_hashes": len(self.hashes),
            "exact_duplicate_records": dupes,
            "char_length": {
                "min": lengths[0] if lengths else 0,
                "median": int(median(lengths)) if lengths else 0,
                "p95": lengths[int(len(lengths) * 0.95)] if lengths else 0,
                "max": lengths[-1] if lengths else 0,
            },
        }


def reject_prose(text: str, *, min_chars: int = 500, max_chars: int = 18000, max_urls: int = 0) -> str | None:
    if len(text) < min_chars:
        return "too_short"
    if len(text) > max_chars:
        return "too_long"
    if BAD_RE.search(text):
        return "bad_marker"
    if HTML_RE.search(text):
        return "html"
    if BOILER_RE.search(text):
        return "boilerplate"
    if COMMERCE_RE.search(text):
        return "commerce"
    if LIST_TABLE_RE.search(text):
        return "list_table"
    if len(URL_RE.findall(text)) > max_urls:
        return "url_dense"
    if not DE_RE.search(text):
        return "weak_de_signal"
    alpha = sum(1 for c in text if c.isalpha()) / max(1, len(text))
    if alpha < 0.35:
        return "low_alpha"
    return None


def download_german_commons_split(
    args: argparse.Namespace,
    out_dir: Path,
    *,
    config: str,
    split: str,
    max_docs: int,
    max_scan: int,
) -> dict[str, Any]:
    name = f"german_commons_{config}_{split}"
    ds = load_dataset("CUI03/german-commons", config, split=split, **hf_kwargs(streaming=True))
    writer = Writer(out_dir, name)
    stats: Counter[str] = Counter()
    t0 = time.time()
    for row in ds:
        stats["seen"] += 1
        text = clean(row.get("text"))
        ocr = row.get("ocr_score")
        ppl = row.get("perplexity")
        tokens = row.get("num_tokens")
        if isinstance(ocr, (int, float)) and ocr < args.min_commons_ocr:
            stats["reject_low_ocr"] += 1
            continue
        if isinstance(ppl, (int, float)) and ppl > args.max_commons_perplexity:
            stats["reject_high_perplexity"] += 1
            continue
        if isinstance(tokens, int) and tokens > args.max_commons_tokens:
            stats["reject_too_many_tokens"] += 1
            continue
        reason = reject_prose(text)
        if reason:
            stats[f"reject_{reason}"] += 1
            writer.reject({"reason": reason, "text": text[:500], "source": row.get("source"), "id": row.get("id")})
            continue
        rec = {
            "source": "CUI03/german-commons",
            "config": config,
            "split": split,
            "id": row.get("id"),
            "source_name": row.get("source"),
            "subset": row.get("subset"),
            "license": parse_license(row.get("license")),
            "num_tokens": tokens,
            "perplexity": ppl,
            "ocr_score": ocr,
            "text": text,
        }
        writer.write(rec, text)
        stats["written"] += 1
        if stats["written"] >= max_docs:
            break
        if stats["seen"] >= max_scan:
            break
    result = {"name": name, "stats": dict(stats), "elapsed_seconds": round(time.time() - t0, 2), **writer.close()}
    return result


def download_natural_questions_de(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    ds = load_dataset("oliverguhr/natural-questions-german", split="train", **hf_kwargs(streaming=True))
    writer = Writer(out_dir, "natural_questions_german")
    stats: Counter[str] = Counter()
    for row in ds:
        stats["seen"] += 1
        q = clean(row.get("query_de"))
        a = clean(row.get("answer_de"))
        text = f"Frage: {q}\nAntwort: {a}"
        reason = reject_prose(text, min_chars=90, max_chars=7000, max_urls=1)
        if reason:
            stats[f"reject_{reason}"] += 1
            writer.reject({"reason": reason, "question": q[:300], "answer": a[:400]})
            continue
        if EN_RE.search(a) and not DE_RE.search(a):
            stats["reject_english_answer"] += 1
            continue
        writer.write(
            {
                "source": "oliverguhr/natural-questions-german",
                "license": "CC-BY-SA-3.0",
                "question": q,
                "answer": a,
                "question_en": clean(row.get("query")),
                "answer_en": clean(row.get("answer")),
            },
            text,
        )
        stats["written"] += 1
        if stats["written"] >= args.max_nq_de:
            break
        if stats["seen"] >= args.max_scan_nq_de:
            break
    return {"name": "natural_questions_german", "stats": dict(stats), **writer.close()}


def download_avemio_config(args: argparse.Namespace, out_dir: Path, config: str) -> dict[str, Any]:
    ds = load_dataset("avemio/German-RAG-SFT-Alpaca-HESSIAN-AI", config, split="train", **hf_kwargs(streaming=True))
    name = f"avemio_german_rag_sft_{config.replace('-', '_')}"
    writer = Writer(out_dir, name)
    stats: Counter[str] = Counter()
    for row in ds:
        stats["seen"] += 1
        system = clean(row.get("System"))
        instruction = clean(row.get("Instruction"))
        response = clean(row.get("Response"))
        text = f"System: {system}\nFrage: {instruction}\nAntwort: {response}"
        reason = reject_prose(text, min_chars=120, max_chars=9000, max_urls=3)
        if reason:
            stats[f"reject_{reason}"] += 1
            writer.reject({"reason": reason, "instruction": instruction[:400], "response": response[:400]})
            continue
        writer.write(
            {
                "source": "avemio/German-RAG-SFT-Alpaca-HESSIAN-AI",
                "config": config,
                "license": "CC-BY-SA-4.0",
                "system": system,
                "question": instruction,
                "answer": response,
            },
            text,
        )
        stats["written"] += 1
        if stats["written"] >= args.max_avemio_per_config:
            break
        if stats["seen"] >= args.max_scan_avemio_per_config:
            break
    return {"name": name, "stats": dict(stats), **writer.close()}


def code_reject(row: dict[str, Any], min_chars: int, max_chars: int) -> list[str]:
    content = clean(row.get("content"))
    path = str(row.get("path") or "")
    license_name = str(row.get("license") or "unknown").lower()
    reasons: list[str] = []
    if license_name not in ALLOWED_CODE_LICENSES:
        reasons.append("license_not_allowed")
    if len(content) < min_chars:
        reasons.append("too_short")
    if len(content) > max_chars:
        reasons.append("too_long")
    if row.get("autogenerated") is True:
        reasons.append("autogenerated_field")
    if VENDOR_PATH_RE.search(path):
        reasons.append("vendor_path")
    if GENERATED_CODE_RE.search(content):
        reasons.append("generated")
    if SECRET_RE.search(content):
        reasons.append("possible_secret")
    try:
        ast.parse(content)
    except SyntaxError:
        reasons.append("python_syntax_error")
    return reasons


def download_codeparrot_plus(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    ds = load_dataset("codeparrot/codeparrot-clean", split="train", **hf_kwargs(streaming=True))
    writer = Writer(out_dir, "codeparrot_clean_python_permissive_plus")
    stats: Counter[str] = Counter()
    licenses: Counter[str] = Counter()
    for row in ds:
        stats["seen"] += 1
        licenses[str(row.get("license") or "unknown")] += 1
        reasons = code_reject(row, min_chars=120, max_chars=30000)
        if reasons:
            for reason in reasons:
                stats[f"reject_{reason}"] += 1
            writer.reject(
                {
                    "reasons": reasons,
                    "path": row.get("path"),
                    "repo_name": row.get("repo_name"),
                    "license": row.get("license"),
                    "preview": clean(row.get("content"))[:500],
                }
            )
            continue
        content = clean(row.get("content"))
        path = str(row.get("path") or "")
        repo = str(row.get("repo_name") or "")
        text = f"<|code|>[python]\n<filename>{path}\n<reponame>{repo}\n{content}\n<|endcode|>"
        writer.write(
            {
                "source": "codeparrot/codeparrot-clean",
                "license": row.get("license"),
                "repo_name": repo,
                "path": path,
                "content": content,
            },
            text,
        )
        stats["written"] += 1
        if stats["written"] >= args.max_codeparrot_plus:
            break
        if stats["seen"] >= args.max_scan_codeparrot_plus:
            break
    result = writer.close()
    result["licenses_seen_top20"] = dict(licenses.most_common(20))
    return {"name": "codeparrot_clean_python_permissive_plus", "stats": dict(stats), **result}


def write_manifest(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("data/training/pretrain_v6_extra_candidates"))
    parser.add_argument("--source", action="append", default=None)
    parser.add_argument("--max-commons-per-split", type=int, default=5000)
    parser.add_argument("--max-scan-commons-per-split", type=int, default=100000)
    parser.add_argument("--min-commons-ocr", type=float, default=95.0)
    parser.add_argument("--max-commons-perplexity", type=float, default=900.0)
    parser.add_argument("--max-commons-tokens", type=int, default=4096)
    parser.add_argument("--max-nq-de", type=int, default=10000)
    parser.add_argument("--max-scan-nq-de", type=int, default=50000)
    parser.add_argument("--max-avemio-per-config", type=int, default=3000)
    parser.add_argument("--max-scan-avemio-per-config", type=int, default=30000)
    parser.add_argument("--max-codeparrot-plus", type=int, default=10000)
    parser.add_argument("--max-scan-codeparrot-plus", type=int, default=250000)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    selected = args.source or [
        "commons_web_wikipedia",
        "commons_web_wikidiscussions",
        "commons_scientific_wikibooks",
        "commons_scientific_wikiversity",
        "natural_questions_de",
        "avemio_qa_without_timedifference",
        "avemio_summarizations",
        "avemio_questions",
        "codeparrot_plus",
    ]
    dispatch = {
        "commons_web_wikipedia": lambda: download_german_commons_split(
            args, args.output_dir, config="web", split="wikipedia", max_docs=args.max_commons_per_split, max_scan=args.max_scan_commons_per_split
        ),
        "commons_web_wikidiscussions": lambda: download_german_commons_split(
            args, args.output_dir, config="web", split="wikidiscussions", max_docs=args.max_commons_per_split, max_scan=args.max_scan_commons_per_split
        ),
        "commons_scientific_wikibooks": lambda: download_german_commons_split(
            args, args.output_dir, config="scientific", split="wikibooks", max_docs=args.max_commons_per_split, max_scan=args.max_scan_commons_per_split
        ),
        "commons_scientific_wikiversity": lambda: download_german_commons_split(
            args, args.output_dir, config="scientific", split="wikiversity", max_docs=args.max_commons_per_split, max_scan=args.max_scan_commons_per_split
        ),
        "natural_questions_de": lambda: download_natural_questions_de(args, args.output_dir),
        "avemio_qa_without_timedifference": lambda: download_avemio_config(args, args.output_dir, "qa-without-timedifference"),
        "avemio_summarizations": lambda: download_avemio_config(args, args.output_dir, "summarizations"),
        "avemio_questions": lambda: download_avemio_config(args, args.output_dir, "questions"),
        "codeparrot_plus": lambda: download_codeparrot_plus(args, args.output_dir),
    }
    manifest: dict[str, Any] = {
        "created_at": now_iso(),
        "output_dir": str(args.output_dir),
        "sources": [],
        "notes": {
            "natural_questions_german": "CC-BY-SA-3.0; keep source-separated until license policy is accepted.",
            "avemio": "CC-BY-SA-4.0; keep source-separated until license policy is accepted.",
            "german_commons": "ODC-By dataset with row-level source license metadata.",
        },
    }
    for name in selected:
        print(f"=== {name} ===", flush=True)
        try:
            result = dispatch[name]()
            result["ok"] = True
        except Exception as exc:
            result = {"name": name, "ok": False, "error": repr(exc)}
            print(f"ERROR {name}: {exc!r}", flush=True)
        manifest["sources"].append(result)
        write_manifest(args.output_dir / "manifest.json", manifest)
    manifest["finished_at"] = now_iso()
    write_manifest(args.output_dir / "manifest.json", manifest)
    print(json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
