#!/usr/bin/env python3
"""Download capped source-separated v6 data candidates and audit them.

This is intentionally a candidate/downloader, not a final mix builder. Every
source is written separately with a manifest and reject samples so we can decide
which sources deserve a larger run.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import urllib.request
import zipfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from statistics import median
from typing import Any, Iterable

from datasets import load_dataset


BAD_RE = re.compile(
    r"\[(?:deleted|removed)\]|onlyfans|discord\.gg|telegram|whatsapp|free karma|"
    r"upvote if|subscribe to|promo code|coupon code|buy now|nsfw|porn|sexkontakte|"
    r"casino|sportwetten|warenkorb|rabattcode|cookie policy",
    re.I,
)
URL_RE = re.compile(r"https?://|www\.", re.I)
HTML_RE = re.compile(r"<\s*/?\s*(html|body|div|script|style|iframe)\b|&(?:amp|gt|lt|quot);", re.I)
CHAT_MARKER_RE = re.compile(r"<\|(?:im_start|im_end|user|assistant|system|endoftext)\|>|_end_of_the_data", re.I)
WORD_RE = re.compile(r"\w+", re.U)
EN_SENT_RE = re.compile(r"\b(the|and|you|write|explain|answer|question|therefore|because)\b", re.I)
CODE_SECRET_RE = re.compile(
    r"(?i)\b(api[_-]?key|secret|token|password|passwd)\b\s*[:=]\s*['\"][^'\"\s]{12,}['\"]|"
    r"-----BEGIN (?:RSA |OPENSSH |EC |DSA )?PRIVATE KEY-----|"
    r"\bAKIA[0-9A-Z]{16}\b"
)
CODE_GENERATED_RE = re.compile(r"(?i)\b(auto[- ]?generated|generated by|do not edit|minified|sourceMappingURL)\b")
CODE_VENDOR_RE = re.compile(r"(?i)(^|/)(node_modules|vendor|dist|build|third_party|externals|site-packages)(/|$)")
ALLOWED_CODE_LICENSES = {"apache-2.0", "mit", "bsd-3-clause", "bsd-2-clause", "isc", "cc0-1.0", "unlicense"}


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def clean(text: Any) -> str:
    text = str(text or "").replace("\r\n", "\n").replace("\r", "\n").replace("\x00", "")
    text = re.sub(r"[ \t]{2,}", " ", text)
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    return text.strip()


def norm_hash(text: str) -> str:
    import hashlib

    norm = re.sub(r"\s+", " ", text).strip().lower()
    return hashlib.sha256(norm.encode("utf-8", errors="replace")).hexdigest()


def hf_kwargs(streaming: bool = True) -> dict[str, Any]:
    kwargs: dict[str, Any] = {"streaming": streaming}
    token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_HUB_TOKEN")
    if token:
        kwargs["token"] = token
    return kwargs


def reject_text(text: str, *, min_chars: int, max_chars: int, min_words: int, max_urls: int) -> str | None:
    if len(text) < min_chars:
        return "too_short"
    if len(text) > max_chars:
        return "too_long"
    if BAD_RE.search(text):
        return "bad_marker"
    if CHAT_MARKER_RE.search(text):
        return "chat_marker"
    if HTML_RE.search(text):
        return "html_or_entity"
    if len(URL_RE.findall(text)) > max_urls:
        return "url_dense"
    words = WORD_RE.findall(text)
    if len(words) < min_words:
        return "too_few_words"
    alpha = sum(1 for c in text if c.isalpha()) / max(len(text), 1)
    if alpha < 0.32:
        return "low_alpha"
    return None


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


class Writer:
    def __init__(self, out_dir: Path, name: str, text_name: str | None = None) -> None:
        self.dir = out_dir / name
        self.dir.mkdir(parents=True, exist_ok=True)
        self.jsonl_path = self.dir / f"{name}.jsonl"
        self.txt_path = self.dir / f"{text_name or name}.txt"
        self.reject_path = self.dir / f"{name}.reject_samples.jsonl"
        self.jsonl = self.jsonl_path.open("w", encoding="utf-8", newline="\n")
        self.txt = self.txt_path.open("w", encoding="utf-8", newline="\n")
        self.rejects: list[dict[str, Any]] = []
        self.hashes: Counter[str] = Counter()
        self.lengths: list[int] = []

    def write(self, rec: dict[str, Any], text: str) -> None:
        self.jsonl.write(json.dumps(rec, ensure_ascii=False, sort_keys=True) + "\n")
        self.txt.write(text.rstrip() + "\n\n")
        h = norm_hash(text)
        self.hashes[h] += 1
        self.lengths.append(len(text))

    def reject(self, sample: dict[str, Any]) -> None:
        if len(self.rejects) < 100:
            self.rejects.append(sample)

    def close(self) -> dict[str, Any]:
        self.jsonl.close()
        self.txt.close()
        if self.rejects:
            self.reject_path.write_text(
                "\n".join(json.dumps(x, ensure_ascii=False, sort_keys=True) for x in self.rejects) + "\n",
                encoding="utf-8",
            )
        dupes = sum(c - 1 for c in self.hashes.values() if c > 1)
        lengths = sorted(self.lengths)
        return {
            "jsonl": str(self.jsonl_path),
            "txt": str(self.txt_path),
            "reject_samples": str(self.reject_path) if self.rejects else None,
            "bytes_jsonl": self.jsonl_path.stat().st_size,
            "bytes_txt": self.txt_path.stat().st_size,
            "unique_hashes": len(self.hashes),
            "exact_duplicate_records": dupes,
            "char_length": {
                "min": lengths[0] if lengths else 0,
                "median": int(median(lengths)) if lengths else 0,
                "p95": lengths[int(len(lengths) * 0.95)] if lengths else 0,
                "max": lengths[-1] if lengths else 0,
            },
        }


def download_oasst_de(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    rows = load_dataset("OpenAssistant/oasst1", split="train", **hf_kwargs(streaming=False))
    by_id: dict[str, dict[str, Any]] = {}
    for row in rows:
        mid = str(row.get("message_id") or "")
        if mid:
            by_id[mid] = dict(row)
    writer = Writer(out_dir, "oasst1_de")
    stats: Counter[str] = Counter()
    for row in rows:
        stats["seen"] += 1
        if row.get("lang") != "de":
            stats["non_de"] += 1
            continue
        if row.get("role") != "assistant":
            stats["not_assistant"] += 1
            continue
        if row.get("deleted") is True:
            stats["deleted"] += 1
            continue
        parent = by_id.get(str(row.get("parent_id") or ""))
        if not parent or parent.get("role") != "prompter" or parent.get("lang") != "de":
            stats["no_de_prompt_parent"] += 1
            continue
        prompt = clean(parent.get("text"))
        answer = clean(row.get("text"))
        reason = reject_text(prompt + "\n" + answer, min_chars=80, max_chars=6000, min_words=10, max_urls=1)
        if reason:
            stats[f"reject_{reason}"] += 1
            writer.reject({"reason": reason, "prompt": prompt[:400], "answer": answer[:400]})
            continue
        rec = {
            "source": "OpenAssistant/oasst1",
            "license": "Apache-2.0",
            "message_id": row.get("message_id"),
            "parent_id": row.get("parent_id"),
            "question": prompt,
            "answer": answer,
        }
        writer.write(rec, f"Frage: {prompt}\nAntwort: {answer}")
        stats["written"] += 1
        if stats["written"] >= args.max_oasst:
            break
    return {"name": "oasst1_de", "stats": dict(stats), **writer.close()}


def write_pair_if_ok(
    writer: Writer,
    stats: Counter[str],
    *,
    source: str,
    license_name: str,
    question: str,
    answer: str,
    rec_id: Any = None,
    max_chars: int = 7000,
) -> bool:
    prompt = clean(question)
    response = clean(answer)
    text = f"Frage: {prompt}\nAntwort: {response}"
    reason = reject_text(text, min_chars=80, max_chars=max_chars, min_words=10, max_urls=1)
    if reason:
        stats[f"reject_{reason}"] += 1
        writer.reject({"reason": reason, "question": prompt[:400], "answer": response[:400], "id": rec_id})
        return False
    if EN_SENT_RE.search(response) and not re.search(r"\b(der|die|das|und|ist|nicht|antwort|frage)\b", response, re.I):
        stats["reject_english_answer"] += 1
        writer.reject({"reason": "english_answer", "question": prompt[:400], "answer": response[:400], "id": rec_id})
        return False
    writer.write(
        {
            "source": source,
            "license": license_name,
            "id": rec_id,
            "question": prompt,
            "answer": response,
        },
        text,
    )
    stats["written"] += 1
    return True


def download_oasst_de_conversations(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    ds = load_dataset("OpenAssistant/OASST-DE", split="train", **hf_kwargs(streaming=True))
    writer = Writer(out_dir, "oasst_de_conversations")
    stats: Counter[str] = Counter()
    for row in ds:
        stats["seen"] += 1
        conv = row.get("conversation") or []
        if not isinstance(conv, list):
            stats["bad_conversation"] += 1
            continue
        last_user = ""
        emitted = False
        for turn in conv:
            if not isinstance(turn, dict):
                continue
            role = turn.get("role")
            text = clean(turn.get("text"))
            if role == "prompter":
                last_user = text
            elif role == "assistant" and last_user and text:
                ok = write_pair_if_ok(
                    writer,
                    stats,
                    source="OpenAssistant/OASST-DE",
                    license_name="Apache-2.0",
                    question=last_user,
                    answer=text,
                    rec_id=f"row{stats['seen']}",
                    max_chars=8000,
                )
                emitted = emitted or ok
                last_user = ""
                if stats["written"] >= args.max_oasst_de_conversations:
                    break
        if not emitted:
            stats["no_written_pair"] += 1
        if stats["written"] >= args.max_oasst_de_conversations:
            break
    return {"name": "oasst_de_conversations", "stats": dict(stats), **writer.close()}


def download_alpaca_gpt4_deutsch(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    ds = load_dataset("FreedomIntelligence/alpaca-gpt4-deutsch", split="train", **hf_kwargs(streaming=True))
    writer = Writer(out_dir, "alpaca_gpt4_deutsch")
    stats: Counter[str] = Counter()
    for row in ds:
        stats["seen"] += 1
        conv = row.get("conversations") or []
        if not isinstance(conv, list):
            stats["bad_conversation"] += 1
            continue
        last_user = ""
        emitted = False
        for turn in conv:
            if not isinstance(turn, dict):
                continue
            role = turn.get("from")
            text = clean(turn.get("value"))
            if role == "human":
                last_user = text
            elif role == "gpt" and last_user and text:
                ok = write_pair_if_ok(
                    writer,
                    stats,
                    source="FreedomIntelligence/alpaca-gpt4-deutsch",
                    license_name="Apache-2.0",
                    question=last_user,
                    answer=text,
                    rec_id=row.get("id"),
                    max_chars=6000,
                )
                emitted = emitted or ok
                last_user = ""
                if stats["written"] >= args.max_alpaca_gpt4_de:
                    break
        if not emitted:
            stats["no_written_pair"] += 1
        if stats["written"] >= args.max_alpaca_gpt4_de:
            break
        if stats["seen"] >= args.max_scan_alpaca_gpt4_de:
            break
    return {"name": "alpaca_gpt4_deutsch", "stats": dict(stats), **writer.close()}


def download_germanquad(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    writer = Writer(out_dir, "germanquad_train")
    stats: Counter[str] = Counter()
    rows: Iterable[dict[str, Any]]
    try:
        rows = load_dataset("deepset/germanquad", split="train", **hf_kwargs(streaming=True))
    except RuntimeError as exc:
        if "Dataset scripts are no longer supported" not in str(exc):
            raise
        cache_dir = out_dir / "_downloads" / "germanquad"
        cache_dir.mkdir(parents=True, exist_ok=True)
        zip_path = cache_dir / "GermanQuAD.zip"
        if not zip_path.is_file():
            urllib.request.urlretrieve("https://germanquad.s3.amazonaws.com/GermanQuAD.zip", zip_path)
        extract_dir = cache_dir / "extracted"
        train_path = extract_dir / "GermanQuAD" / "GermanQuAD_train.json"
        if not train_path.is_file():
            with zipfile.ZipFile(zip_path) as zf:
                zf.extractall(extract_dir)

        def iter_germanquad_json() -> Iterable[dict[str, Any]]:
            payload = json.loads(train_path.read_text(encoding="utf-8"))
            for article in payload.get("data", []):
                title = article.get("title")
                for paragraph in article.get("paragraphs", []):
                    context = paragraph.get("context")
                    document_id = paragraph.get("document_id")
                    for qa in paragraph.get("qas", []):
                        yield {
                            "id": qa.get("id"),
                            "title": title,
                            "document_id": document_id,
                            "context": context,
                            "question": qa.get("question"),
                            "answers": {"text": [a.get("text") for a in qa.get("answers", []) if a.get("text")]},
                        }

        rows = iter_germanquad_json()
    for row in rows:
        stats["seen"] += 1
        question = clean(row.get("question"))
        context = clean(row.get("context"))
        answers = row.get("answers") or {}
        answer_texts = answers.get("text") if isinstance(answers, dict) else None
        answer = clean(answer_texts[0] if answer_texts else "")
        if not question or not answer or not context:
            stats["missing_field"] += 1
            continue
        text = f"Kontext: {context}\nFrage: {question}\nAntwort: {answer}"
        reason = reject_text(text, min_chars=120, max_chars=8000, min_words=12, max_urls=1)
        if reason:
            stats[f"reject_{reason}"] += 1
            writer.reject({"reason": reason, "question": question[:400], "context": context[:400]})
            continue
        writer.write(
            {
                "source": "deepset/germanquad",
                "license": "CC-BY-4.0",
                "id": row.get("id"),
                "title": row.get("title"),
                "question": question,
                "answer": answer,
                "context": context,
            },
            text,
        )
        stats["written"] += 1
        if stats["written"] >= args.max_germanquad:
            break
    return {"name": "germanquad_train", "stats": dict(stats), **writer.close()}


def download_fineweb2_de(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    ds = load_dataset("HuggingFaceFW/fineweb-2", "deu_Latn", split="train", **hf_kwargs(streaming=True))
    writer = Writer(out_dir, "fineweb2_deu_latn")
    stats: Counter[str] = Counter()
    for row in ds:
        stats["seen"] += 1
        text = clean(row.get("text"))
        reason = reject_text(text, min_chars=300, max_chars=25000, min_words=45, max_urls=3)
        if reason:
            stats[f"reject_{reason}"] += 1
            writer.reject({"reason": reason, "text": text[:500]})
            continue
        writer.write(
            {
                "source": "HuggingFaceFW/fineweb-2",
                "config": "deu_Latn",
                "license": "ODC-By-1.0-per-card",
                "text": text,
                "id": row.get("id"),
                "dump": row.get("dump"),
                "url": row.get("url"),
            },
            text,
        )
        stats["written"] += 1
        if stats["written"] >= args.max_fineweb2:
            break
        if stats["seen"] >= args.max_scan_fineweb2:
            break
    return {"name": "fineweb2_deu_latn", "stats": dict(stats), **writer.close()}


def download_openmath(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    ds = load_dataset("nvidia/OpenMathInstruct-2", split="train", **hf_kwargs(streaming=True))
    writer = Writer(out_dir, "openmathinstruct2_capped")
    stats: Counter[str] = Counter()
    for row in ds:
        stats["seen"] += 1
        problem = clean(row.get("problem") or row.get("question") or row.get("input"))
        solution = clean(row.get("solution") or row.get("generated_solution") or row.get("output") or row.get("answer"))
        expected = clean(row.get("expected_answer") or row.get("final_answer"))
        if not problem or not solution:
            stats["missing_field"] += 1
            continue
        text = f"Problem: {problem}\nLoesung: {solution}"
        if expected:
            text += f"\nAntwort: {expected}"
        reason = reject_text(text, min_chars=120, max_chars=10000, min_words=15, max_urls=2)
        if reason:
            stats[f"reject_{reason}"] += 1
            writer.reject({"reason": reason, "problem": problem[:400], "solution": solution[:400]})
            continue
        writer.write(
            {
                "source": "nvidia/OpenMathInstruct-2",
                "license": "CC-BY-4.0",
                "problem": problem,
                "solution": solution,
                "expected_answer": expected,
            },
            text,
        )
        stats["written"] += 1
        if stats["written"] >= args.max_openmath:
            break
        if stats["seen"] >= args.max_scan_openmath:
            break
    return {"name": "openmathinstruct2_capped", "stats": dict(stats), **writer.close()}


def reject_codeparrot(row: dict[str, Any], min_chars: int, max_chars: int) -> list[str]:
    content = clean(row.get("content"))
    path = str(row.get("path") or "")
    license_name = str(row.get("license") or "unknown").lower()
    reasons: list[str] = []
    if license_name not in ALLOWED_CODE_LICENSES:
        reasons.append("license_not_allowed")
    if len(content) < min_chars:
        reasons.append("too_short")
    if len(content) > max_chars:
        reasons.append("too_long")
    if row.get("autogenerated") is True:
        reasons.append("autogenerated_field")
    if CODE_VENDOR_RE.search(path):
        reasons.append("vendor_path")
    if CODE_GENERATED_RE.search(content):
        reasons.append("generated")
    if CODE_SECRET_RE.search(content):
        reasons.append("possible_secret")
    try:
        ast.parse(content)
    except SyntaxError:
        reasons.append("python_syntax_error")
    return reasons


def download_codeparrot(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    ds = load_dataset("codeparrot/codeparrot-clean", split="train", **hf_kwargs(streaming=True))
    writer = Writer(out_dir, "codeparrot_clean_python_permissive")
    stats: Counter[str] = Counter()
    licenses: Counter[str] = Counter()
    for row in ds:
        stats["seen"] += 1
        licenses[str(row.get("license") or "unknown")] += 1
        reasons = reject_codeparrot(row, min_chars=80, max_chars=30000)
        if reasons:
            for reason in reasons:
                stats[f"reject_{reason}"] += 1
            writer.reject(
                {
                    "reasons": reasons,
                    "path": row.get("path"),
                    "repo_name": row.get("repo_name"),
                    "license": row.get("license"),
                    "preview": clean(row.get("content"))[:500],
                }
            )
            continue
        content = clean(row.get("content"))
        path = str(row.get("path") or "")
        repo = str(row.get("repo_name") or "")
        text = f"<|code|>[python]\n<filename>{path}\n<reponame>{repo}\n{content}\n<|endcode|>"
        writer.write(
            {
                "source": "codeparrot/codeparrot-clean",
                "license": row.get("license"),
                "repo_name": repo,
                "path": path,
                "content": content,
            },
            text,
        )
        stats["written"] += 1
        if stats["written"] >= args.max_codeparrot:
            break
        if stats["seen"] >= args.max_scan_codeparrot:
            break
    result = writer.close()
    result["licenses_seen_top20"] = dict(licenses.most_common(20))
    return {"name": "codeparrot_clean_python_permissive", "stats": dict(stats), **result}


DOWNLOADERS = {
    "alpaca_gpt4_de": download_alpaca_gpt4_deutsch,
    "oasst_de": download_oasst_de,
    "oasst_de_conversations": download_oasst_de_conversations,
    "germanquad": download_germanquad,
    "fineweb2_de": download_fineweb2_de,
    "openmathinstruct2": download_openmath,
    "codeparrot": download_codeparrot,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("data/training/pretrain_v6_candidates"))
    parser.add_argument("--source", action="append", choices=sorted(DOWNLOADERS), default=None)
    parser.add_argument("--max-oasst", type=int, default=5000)
    parser.add_argument("--max-oasst-de-conversations", type=int, default=10000)
    parser.add_argument("--max-alpaca-gpt4-de", type=int, default=20000)
    parser.add_argument("--max-scan-alpaca-gpt4-de", type=int, default=60000)
    parser.add_argument("--max-germanquad", type=int, default=5000)
    parser.add_argument("--max-fineweb2", type=int, default=5000)
    parser.add_argument("--max-scan-fineweb2", type=int, default=60000)
    parser.add_argument("--max-openmath", type=int, default=5000)
    parser.add_argument("--max-scan-openmath", type=int, default=60000)
    parser.add_argument("--max-codeparrot", type=int, default=5000)
    parser.add_argument("--max-scan-codeparrot", type=int, default=80000)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    selected = args.source or list(DOWNLOADERS)
    manifest: dict[str, Any] = {
        "created_at": now_iso(),
        "output_dir": str(args.output_dir),
        "sources": [],
        "caps": {
            "max_oasst": args.max_oasst,
            "max_oasst_de_conversations": args.max_oasst_de_conversations,
            "max_alpaca_gpt4_de": args.max_alpaca_gpt4_de,
            "max_germanquad": args.max_germanquad,
            "max_fineweb2": args.max_fineweb2,
            "max_openmath": args.max_openmath,
            "max_codeparrot": args.max_codeparrot,
        },
    }
    for name in selected:
        print(f"=== {name} ===", flush=True)
        try:
            result = DOWNLOADERS[name](args, args.output_dir)
            result["ok"] = True
        except Exception as exc:
            result = {"name": name, "ok": False, "error": repr(exc)}
            print(f"ERROR {name}: {exc!r}", flush=True)
        manifest["sources"].append(result)
        write_json(args.output_dir / "manifest.json", manifest)
    manifest["finished_at"] = now_iso()
    write_json(args.output_dir / "manifest.json", manifest)
    print(json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
