"""Ask-LLM code quality scoring against a LocalAI / llama-cpp-server endpoint.

Combines the <reponame>-marker reader + code rubric from ask_llm_code.py
with the direct HTTP + ThreadPoolExecutor approach from ask_llm_local.py.
Avoids distilabel / OpenRouter entirely — runs against any OpenAI-compatible
local inference server (LocalAI, vLLM, llama-cpp-server).

Memory-safe design:
  - Binary-mode file reading with exact byte-offset posix_fadvise(DONTNEED)
    every 32 MB so the kernel evicts already-read pages instead of caching the
    full 57 GB file.  Page-cache growth is bounded to ~32 MB at a time.
  - Streaming doc generator with a bounded queue (parallel*4 items max in RAM).
    Never loads all docs into memory before scoring begins.
  - Container memory limit (docker update --memory 4g) acts as a safety net:
    if the container exceeds 4 GB the kernel kills the container, not the host.

Usage (inside auralis-downloader container):
    python3 /staging/scripts/ask_llm_code_local.py \\
        --input  /staging/raw/the_stack_v2_python/the_stack_v2_python.txt \\
        --output /staging/cleaned/ask_llm/the_stack_python_local.jsonl \\
        --base-url http://172.17.0.1:8765/v1 \\
        --model qwen3.6-35b-a3b \\
        --parallel 8 --resume
"""
from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import re
import sys
import time
from pathlib import Path
from typing import Iterator

import requests


# Code-specific 1-5 rubric (same as ask_llm_code.py for consistent calibration).
SCORE_PROMPT = """\
You are a strict data-quality evaluator for an LLM code-pretraining corpus.
Rate the Python file on a 1-5 scale based on its value for training a model
to write idiomatic, well-structured Python.

1 = useless: empty, near-empty, only license headers, only imports, broken
    syntax, autogenerated boilerplate (Django migrations, gRPC stubs,
    `__init__.py` re-exports, alembic versions), or trivial 1-liner scripts.
2 = low quality: unstructured top-level code, no functions/classes, magic
    numbers, terrible naming, copy-paste duplication, no docs at all.
3 = mediocre: works but minimal docs, basic structure, missing type hints,
    occasional anti-patterns (`except: pass`, `eval`, mutable default args).
4 = clean idiomatic Python: proper functions/classes, docstrings present,
    type hints OR clear naming, error handling, follows PEP8 conventions.
5 = exemplary library-quality code: fully documented, type-annotated, tests
    visible, educational, demonstrates good Python idioms a learner should see.

Repository: {reponame}

Code (first {head_chars} chars):
{code_head}

Reply with this exact format on a single line:
Score: <digit from 1 to 5>"""

# posix_fadvise constants (defined in Python 3.3+ on Linux)
_FADV_SEQUENTIAL = getattr(os, "POSIX_FADV_SEQUENTIAL", 2)
_FADV_DONTNEED   = getattr(os, "POSIX_FADV_DONTNEED",   4)
_FADV_NOREUSE    = getattr(os, "POSIX_FADV_NOREUSE",    5)

# Disabled: posix_fadvise(DONTNEED) on btrfs/NVMe causes "Invalid Field in Command"
# errors (291 logged) that can freeze the kernel I/O stack under sustained load.
# Ollama uses only ~3.8 GB RAM so page-cache pressure is not a concern.
_HAVE_FADVISE = False


def _fadvise(fd: int, offset: int, length: int, advice: int) -> None:
    """Call posix_fadvise silently; ignore if unavailable or errors."""
    if _HAVE_FADVISE and length > 0:
        try:
            os.posix_fadvise(fd, offset, length, advice)
        except OSError:
            pass


def read_repo_marker_docs(
    path: Path, marker: str = "<reponame>"
) -> Iterator[tuple[int, str, str]]:
    """Stream the_stack-style files separated by `<reponame>OWNER/REPO\\n`.
    Yields (doc_id, reponame, code_text).

    Opens in BINARY mode so byte offsets are exact.  Calls
    posix_fadvise(DONTNEED) every DONTNEED_EVERY bytes so the kernel evicts
    already-processed pages.  On a 57 GB file with 62 GB RAM this keeps
    page-cache growth bounded instead of filling all available memory.
    """
    DONTNEED_EVERY = 32 * 1024 * 1024   # drop cache every 32 MB (not advisory 512 MB)
    marker_bytes   = marker.encode()

    buf: list[str] = []
    current_repo: str | None = None
    n = 0
    byte_pos = 0
    last_dontneed = 0

    with path.open("rb") as f:
        fd = f.fileno()
        _fadvise(fd, 0, 0, _FADV_SEQUENTIAL)   # enable kernel read-ahead

        for raw_line in f:
            byte_pos += len(raw_line)

            # Drop already-read pages every 32 MB (exact byte offset).
            if byte_pos - last_dontneed >= DONTNEED_EVERY:
                _fadvise(fd, last_dontneed, byte_pos - last_dontneed, _FADV_DONTNEED)
                _fadvise(fd, last_dontneed, byte_pos - last_dontneed, _FADV_NOREUSE)
                last_dontneed = byte_pos

            line = raw_line.decode("utf-8", errors="replace")
            if raw_line.startswith(marker_bytes):
                if current_repo is not None and buf:
                    yield n, current_repo, "".join(buf)
                    n += 1
                    buf.clear()
                current_repo = line[len(marker):].rstrip("\n\r")
            else:
                if current_repo is not None:
                    buf.append(line)

        # Flush last document.
        if current_repo is not None and buf:
            yield n, current_repo, "".join(buf)


def score_one(
    session: requests.Session,
    base_url: str,
    model: str,
    doc: dict,
    max_tokens: int,
    temperature: float,
    timeout: int,
) -> dict:
    """Score a single doc via HTTP. Returns JSONL row."""
    try:
        r = session.post(
            f"{base_url.rstrip('/')}/chat/completions",
            json={
                "model": model,
                "messages": [{"role": "user", "content": doc["instruction"]}],
                "max_tokens": max_tokens,
                "temperature": temperature,
            },
            timeout=timeout,
        )
        r.raise_for_status()
        j = r.json()
        msg = j["choices"][0]["message"]
        # LocalAI thinking-mode models may put answer in reasoning when content is empty.
        text = (
            (msg.get("content") or "").strip()
            or (msg.get("reasoning") or "").strip()
            or (msg.get("reasoning_content") or "").strip()
        )
        score: int | None = None
        m = re.search(r"[1-5]", text)
        if m:
            score = int(m.group())
    except Exception as e:
        text = f"ERROR: {type(e).__name__}: {e}"
        score = None
    return {
        "doc_id": doc["doc_id"],
        "reponame": doc["reponame"],
        "score": score,
        "raw_response": text,
        "head": doc["head"],
        "length_chars": doc["length_chars"],
        "kept": score is not None and score >= doc["_threshold"],
    }


def main() -> int:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--input",  type=Path, required=True)
    p.add_argument("--output", type=Path, required=True)
    p.add_argument("--max-docs",    type=int,   default=0,
                   help="Max docs to score (default 0 = all).")
    p.add_argument("--threshold",   type=int,   default=3)
    p.add_argument("--head-chars",  type=int,   default=2000)
    p.add_argument("--min-chars",   type=int,   default=100)
    p.add_argument("--max-chars",   type=int,   default=50_000)
    p.add_argument("--marker",      default="<reponame>")
    p.add_argument("--model",       default="qwen3.6-35b-a3b")
    p.add_argument("--base-url",    default="http://172.17.0.1:8765/v1")
    p.add_argument("--parallel",    type=int,   default=8)
    p.add_argument("--max-tokens",  type=int,   default=32)
    p.add_argument("--temperature", type=float, default=0.05)
    p.add_argument("--timeout",     type=int,   default=120)
    p.add_argument("--chunk-size",  type=int,   default=1000,
                   help="Progress report every N scored docs.")
    p.add_argument("--resume", action="store_true",
                   help="Skip doc_ids already in output file.")
    args = p.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)

    # Resume: load already-done doc_ids (small set, fine to keep in RAM).
    done_ids: set[int] = set()
    if args.resume and args.output.exists():
        with args.output.open("r", encoding="utf-8") as f:
            for line in f:
                try:
                    rec = json.loads(line)
                    if rec.get("doc_id") is not None:
                        done_ids.add(rec["doc_id"])
                except json.JSONDecodeError:
                    continue
        print(f"Resume: {len(done_ids)} doc_ids already done.", flush=True)
    elif args.output.exists():
        args.output.write_text("")

    # Connectivity check before the slow file traversal.
    sess = requests.Session()
    print(f"Pinging {args.base_url} ...", flush=True)
    try:
        ping = sess.get(f"{args.base_url.rstrip('/')}/models", timeout=10)
        ping.raise_for_status()
    except Exception as e:
        sys.exit(f"FATAL: cannot reach {args.base_url}: {e}")
    print(f"  endpoint OK, model={args.model!r}", flush=True)

    fadvise_status = "posix_fadvise active (32 MB DONTNEED)" if _HAVE_FADVISE else "posix_fadvise unavailable"
    print(f"  {fadvise_status}", flush=True)

    max_limit: float = args.max_docs if args.max_docs > 0 else float("inf")
    max_queued = args.parallel * 4   # bounded queue: never > this many doc dicts in RAM

    n_kept = n_total = 0
    n_too_short = n_too_long = n_resumed = 0
    histogram: dict[int | str, int] = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, "?": 0}
    chunk_size    = max(args.chunk_size, 1)
    chunk_counter = 0
    chunk_kept    = 0
    t0 = time.time()

    def doc_source() -> Iterator[dict]:
        nonlocal n_too_short, n_too_long, n_resumed
        for doc_id, reponame, code in read_repo_marker_docs(args.input, args.marker):
            if doc_id >= max_limit:
                return
            if doc_id in done_ids:
                n_resumed += 1
                continue
            L = len(code)
            if L < args.min_chars:
                n_too_short += 1
                continue
            if args.max_chars and L > args.max_chars:
                n_too_long += 1
                continue
            yield {
                "doc_id": doc_id,
                "reponame": reponame,
                "instruction": SCORE_PROMPT.format(
                    reponame=reponame,
                    head_chars=args.head_chars,
                    code_head=code[:args.head_chars],
                ),
                "head": code[:200],
                "length_chars": L,
                "_threshold": args.threshold,
            }

    print(f"Streaming {args.input} ...", flush=True)

    with args.output.open("a", encoding="utf-8") as out_f, \
         concurrent.futures.ThreadPoolExecutor(max_workers=args.parallel) as ex:

        source = doc_source()
        pending: dict[concurrent.futures.Future, None] = {}
        source_exhausted = False

        def fill_queue() -> None:
            nonlocal source_exhausted
            while len(pending) < max_queued and not source_exhausted:
                try:
                    doc = next(source)
                    fut = ex.submit(
                        score_one, sess, args.base_url, args.model, doc,
                        args.max_tokens, args.temperature, args.timeout,
                    )
                    pending[fut] = None
                except StopIteration:
                    source_exhausted = True
                    break

        fill_queue()
        while pending:
            done_futs = concurrent.futures.wait(
                list(pending), return_when=concurrent.futures.FIRST_COMPLETED
            ).done
            for fut in done_futs:
                rec = fut.result()
                del pending[fut]
                rec_out = {k: v for k, v in rec.items() if k != "_threshold"}
                n_total += 1
                histogram[rec["score"] if rec["score"] in histogram else "?"] += 1
                if rec["kept"]:
                    n_kept += 1
                    chunk_kept += 1
                out_f.write(json.dumps(rec_out, ensure_ascii=False) + "\n")
                chunk_counter += 1
                if chunk_counter >= chunk_size:
                    out_f.flush()
                    elapsed = time.time() - t0
                    rate    = n_total / elapsed if elapsed > 0 else 0
                    print(
                        f"  {n_total} scored  {chunk_kept}/{chunk_size} kept  "
                        f"{rate:.2f} doc/s  {elapsed/3600:.2f}h elapsed",
                        flush=True,
                    )
                    chunk_counter = 0
                    chunk_kept    = 0
            fill_queue()

    elapsed = time.time() - t0
    print(flush=True)
    print(f"=== ask-llm-code-local ({args.model}) ===")
    print(f"  input :  {args.input}")
    print(f"  output:  {args.output}")
    print(f"  scored:  {n_total} files in {elapsed/60:.1f} min")
    if n_resumed:    print(f"  resumed: {n_resumed} previously-done files skipped")
    if n_too_short or n_too_long:
        print(f"  filtered: {n_too_short} too-short, {n_too_long} too-long")
    print(f"  kept  :  {n_kept} / {n_total} (≥{args.threshold}) — "
          f"{100*n_kept/max(n_total,1):.1f}%")
    print("  histogram:")
    for k in [1, 2, 3, 4, 5, "?"]:
        bar = "█" * min(histogram[k], 60)
        print(f"    {k}: {histogram[k]:6d}  {bar}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
