"""Ask-LLM quality scoring for code corpora (the_stack-v2 style).

Same Sachdeva-et-al pattern as ask_llm_deepseek.py but with a code-specific
1-5 rubric and a reader for the_stack v2 marker format
(`<reponame>OWNER/REPO\\n<file content>\\n<reponame>...\\n`).

The rubric weights factors that actually matter for LLM training on code:
* idiomatic constructs vs anti-patterns
* meaningful structure (functions/classes) vs top-level scripts
* docstrings/comments vs naked code
* presence of type hints
* not auto-generated boilerplate (Django migrations, gRPC stubs, etc.)

Usage:
    OPENROUTER_API_KEY=sk-or-... \\
    python scripts/data/pipeline/ask_llm_code.py \\
        --input  /staging/raw/the_stack_v2_python/the_stack_v2_python.txt \\
        --output /staging/cleaned/ask_llm/the_stack_v2_python_5k_qwen36_scored.jsonl \\
        --max-docs 5000 \\
        --threshold 3
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Iterable


# Code-specific rubric. The "1 = useless" bucket is intentionally generous
# because the_stack contains many auto-generated stubs that should be
# filtered out before pretraining (Sachdeva 2024 Table 3 shows code-trained
# models benefit MORE from aggressive low-quality filtering than text models).
SCORE_PROMPT = """\
You are a strict data-quality evaluator for an LLM code-pretraining corpus.
Rate the Python file on a 1-5 scale based on its value for training a model
to write idiomatic, well-structured Python.

1 = useless: empty, near-empty, only license headers, only imports, broken
    syntax, autogenerated boilerplate (Django migrations, gRPC stubs,
    `__init__.py` re-exports, alembic versions), or trivial 1-liner scripts.
2 = low quality: unstructured top-level code, no functions/classes, magic
    numbers, terrible naming, copy-paste duplication, no docs at all.
3 = mediocre: works but minimal docs, basic structure, missing type hints,
    occasional anti-patterns (`except: pass`, `eval`, mutable default args).
4 = clean idiomatic Python: proper functions/classes, docstrings present,
    type hints OR clear naming, error handling, follows PEP8 conventions.
5 = exemplary library-quality code: fully documented, type-annotated, tests
    visible, educational, demonstrates good Python idioms a learner should see.

Repository: {reponame}

Code (first {head_chars} chars):
{code_head}

Reply with this exact format on a single line:
Score: <digit from 1 to 5>"""


def read_repo_marker_docs(path: Path, marker: str = "<reponame>") -> Iterable[tuple[int, str, str]]:
    """Stream the_stack-style files separated by `<reponame>OWNER/REPO\\n`.
    Yields (doc_id, reponame, code_text). The reponame line is stripped from
    the code text so the rubric isn't biased by repo names appearing twice."""
    buf: list[str] = []
    current_repo: str | None = None
    n = 0
    with path.open("r", encoding="utf-8", errors="replace") as f:
        for line in f:
            if line.startswith(marker):
                # Flush previous file
                if current_repo is not None and buf:
                    code = "".join(buf)
                    yield n, current_repo, code
                    n += 1
                    buf.clear()
                current_repo = line[len(marker):].strip()
            else:
                if current_repo is not None:
                    buf.append(line)
        # Flush trailing
        if current_repo is not None and buf:
            code = "".join(buf)
            yield n, current_repo, code


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--input", type=Path, required=True)
    p.add_argument("--output", type=Path, required=True)
    p.add_argument("--max-docs", type=int, default=100)
    p.add_argument("--threshold", type=int, default=3,
                   help="keep files with score >= threshold (default 3)")
    p.add_argument("--head-chars", type=int, default=2000,
                   help="show this many chars of the file to the scorer (default 2000 — "
                        "code is denser than prose, this is roughly the first ~80 lines)")
    p.add_argument("--min-chars", type=int, default=100,
                   help="Skip files with fewer than this many chars before scoring "
                        "(default 100 — drops empty files and trivial __init__.py).")
    p.add_argument("--max-chars", type=int, default=50000,
                   help="Skip files with more than this many chars (default 50000 — "
                        "drops vendored bundles, generated protobuf, etc.)")
    p.add_argument("--marker", default="<reponame>",
                   help="The reponame separator marker (default '<reponame>')")
    p.add_argument("--model", default="qwen/qwen3.6-35b-a3b",
                   help="OpenRouter model id. Default matches text scorer for "
                        "consistent calibration. Reasoning auto-disabled.")
    p.add_argument("--batch-size", type=int, default=8)
    p.add_argument("--chunk-size", type=int, default=500,
                   help="Process this many files per pipeline.run(). Smaller = "
                        "better crash-resumability + more overhead. Default 500.")
    p.add_argument("--resume", action="store_true",
                   help="If output exists, skip doc_ids already present.")
    args = p.parse_args()

    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        sys.exit("FATAL: OPENROUTER_API_KEY env var is required")

    from distilabel.pipeline import Pipeline
    from distilabel.steps import LoadDataFromDicts
    from distilabel.steps.tasks import TextGeneration
    from distilabel.models import OpenAILLM

    args.output.parent.mkdir(parents=True, exist_ok=True)
    done_ids: set[int] = set()
    if args.resume and args.output.exists():
        with args.output.open("r", encoding="utf-8") as f:
            for line in f:
                try:
                    rec = json.loads(line)
                    if rec.get("doc_id") is not None:
                        done_ids.add(rec["doc_id"])
                except json.JSONDecodeError:
                    continue
        print(f"Resume: {len(done_ids)} doc_ids already in output, will skip them.",
              flush=True)
    elif args.output.exists() and not args.resume:
        args.output.write_text("")

    print(f"Reading {args.input} ...", flush=True)
    docs = []
    n_too_short = 0
    n_too_long = 0
    n_resumed = 0
    for doc_id, reponame, code in read_repo_marker_docs(args.input, args.marker):
        if doc_id >= args.max_docs:
            break
        if doc_id in done_ids:
            n_resumed += 1
            continue
        L = len(code)
        if args.min_chars and L < args.min_chars:
            n_too_short += 1
            continue
        if args.max_chars and L > args.max_chars:
            n_too_long += 1
            continue
        docs.append({
            "doc_id": doc_id,
            "reponame": reponame,
            "instruction": SCORE_PROMPT.format(
                reponame=reponame,
                head_chars=args.head_chars,
                code_head=code[:args.head_chars],
            ),
            "head": code[:200],
            "length_chars": L,
        })
    print(f"  {len(docs)} files prepared", flush=True)
    if n_too_short or n_too_long:
        print(f"  pre-filtered: {n_too_short} too-short (<{args.min_chars}), "
              f"{n_too_long} too-long (>{args.max_chars})", flush=True)
    if n_resumed:
        print(f"  resumed: {n_resumed} doc_ids already done, skipped", flush=True)

    if not docs:
        print("  nothing to score, exiting.", flush=True)
        return 0

    llm = OpenAILLM(
        api_key=api_key,
        base_url="https://openrouter.ai/api/v1",
        model=args.model,
        generation_kwargs={
            "temperature": 0.05,
            "max_new_tokens": 16,
            "extra_body": {"reasoning": {"enabled": False}},
        },
    )

    chunk_size = args.chunk_size if args.chunk_size > 0 else len(docs)
    n_chunks = (len(docs) + chunk_size - 1) // chunk_size

    n_kept = 0
    n_total = 0
    histogram = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, "?": 0}

    def _iter_rows(distiset):
        for leaf_name, leaf in distiset.items():
            for split_name, ds in leaf.items():
                for row in ds:
                    yield row

    print(f"Processing {len(docs)} files in {n_chunks} chunk(s) of "
          f"{chunk_size} (streaming-append, resumable).", flush=True)

    with args.output.open("a", encoding="utf-8") as out_f:
        for chunk_idx in range(n_chunks):
            chunk_docs = docs[chunk_idx * chunk_size:(chunk_idx + 1) * chunk_size]
            print(f"  chunk {chunk_idx + 1}/{n_chunks}: "
                  f"{len(chunk_docs)} files ...", flush=True)

            with Pipeline(name="ask-llm-code") as pipeline:
                loader = LoadDataFromDicts(data=chunk_docs)
                score_step = TextGeneration(
                    llm=llm,
                    input_batch_size=args.batch_size,
                    num_generations=1,
                )
                loader >> score_step

            distiset = pipeline.run(use_cache=False)

            chunk_kept = 0
            for row in _iter_rows(distiset):
                n_total += 1
                generation = (row.get("generation") or "").strip()
                score = None
                for ch in generation:
                    if ch in "12345":
                        score = int(ch)
                        break
                histogram[score if score in histogram else "?"] += 1
                rec = {
                    "doc_id": row.get("doc_id"),
                    "reponame": row.get("reponame"),
                    "score": score,
                    "raw_response": generation,
                    "head": row.get("head"),
                    "length_chars": row.get("length_chars"),
                    "kept": score is not None and score >= args.threshold,
                }
                if rec["kept"]:
                    n_kept += 1
                    chunk_kept += 1
                out_f.write(json.dumps(rec, ensure_ascii=False) + "\n")
            out_f.flush()
            print(f"    chunk {chunk_idx + 1} done: {chunk_kept} kept "
                  f"(running total: {n_kept}/{n_total})", flush=True)

    print()
    print(f"=== Ask-LLM-Code (Qwen3.6) results ===")
    print(f"  scored:  {n_total} files (this run)")
    if n_resumed:
        print(f"  resumed: {n_resumed} previously-done files not re-scored")
    print(f"  kept:    {n_kept} (threshold ≥ {args.threshold}) — "
          f"{100*n_kept/max(n_total,1):.1f}%")
    print(f"  output:  {args.output}")
    print(f"  histogram:")
    for k in [1, 2, 3, 4, 5, "?"]:
        bar = "█" * histogram[k]
        print(f"    {k}: {histogram[k]:4d}  {bar}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
